export const PROJECT_FORM_VISIBILITY = 'PROJECT_FORM_VISIBILITY';
export const PROJECT_GET_PROJECTS = 'PROJECT_GET_PROJECTS';
export const PROJECT_SET_PROJECT = 'PROJECT_SET_PROJECT';
export const PROJECT_NAME_EMPTY_ALERT = 'PROJECT_NAME_EMPTY_ALERT';
export const PROJECT_RESET_NAME_EMPTY_ALERT = 'PROJECT_RESET_NAME_EMPTY_ALERT';
