export const PROJECT_FORM_VISIBILITY = 'PROJECT_FORM_VISIBILITY';
export const PROJECT_GET_PROJECTS = 'PROJECT_GET_PROJECTS';
export const PROJECT_SET_PROJECT = 'PROJECT_SET_PROJECT';
export const PROJECT_NAME_EMPTY_ALERT = 'PROJECT_NAME_EMPTY_ALERT';
export const PROJECT_SELECTED_PROJECT = 'PROJECT_SELECTED_PROJECT';
export const PROJECT_DELETE_PROJECT = 'PROJECT_DELETE_PROJECT';

export const TASK_PROJECT_TASKS = 'TASK_PROJECT_TASKS';
export const TASK_CREATE_TASK = 'TASK_CREATE_TASK';
export const TASK_VALIDATE_TASK = 'TASK_VALIDATE_TASK';
export const TASK_DELETE_TASK = 'TASK_DELETE_TASK';
export const TASK_CHANGE_TASK_STATE = 'TASK_CHANGE_TASK_STATE';
export const TASK_CURRENT_TASK = 'TASK_CURRENT_TASK';
export const TASK_UPDATE_TASK = 'TASK_UPDATE_TASK';
export const TASK_RESET_CURRENT_TASK = 'TASK_RESET_CURRENT_TASK';

export const ALERT_SHOW_ALERT = 'ALERT_SHOW_ALERT';
export const ALERT_HIDE_ALERT = 'ALERT_HIDE_ALERT';

export const AUTH_REGISTRY_OK = 'AUTH_REGISTRY_OK';
export const AUTH_REGISTRY_ERROR = 'AUTH_REGISTRY_ERROR';
export const AUTH_GET_USER = 'AUTH_GET_USER';
export const AUTH_LOGIN_OK = 'AUTH_LOGIN_OK';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';
export const AUTH_CLOSE_SESSION = 'AUTH_CLOSE_SESSION';
